receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  otlphttp/tempo:
    endpoint: http://tempo:3200
    traces_endpoint: http://tempo:3200/api/traces

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo]
